Dextra/pose estimation
Unity-Technologies/Unity-Robotics-Hub pull request #122
Opened 2021-02-06 00:46 UTC by sarahwolf32

Pose Estimation Pick & Place Demo

DO NOT MERGE - we are still waiting on the next perception package release, which this will depend on. Due to this, when testing the project, be sure to uninstall the perception package, clone it from [master](https://github.com/Unity-Technologies/com.unity.perception), and reinstall from disk.

Feedback welcome!

Also, we're happy to change formatting details to better match the Robotics Hub, feedback on that welcome.

2021-02-09 02:48 UTC, sarah-gibson requested changes

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +**Action**: The ROS TCP connection needs to be created. In the top menu bar in the Unity Editor, select `Robotics -> ROS Settings`. Find the IP address of your ROS machine.
Looks a bit weird that these two actions are at a different hierarchy

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +**Note**: While using the ROS Settings menu is the suggested workflow, you may still manually create a GameObject with an attached ROSConnection component.
This may be confusing, since we updated the instructions on this old tutorial to use this workflow too. I suggest deleting.

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +* **Action**: Return to Unity. Select the `ROSObjects/Publisher` GameObject. Assign the `ur3_with_gripper` GameObject to the `Robot` field. Drag and drop the `Cube` GameObject from the _**Hierarchy**
I don't understand what the Simulation Scenario has to do with the TrajectoryPlanner. Was that explained somewhere and I missed it?

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +**Note**: The launch file may throw errors regarding `[controller_spawner-5] process has died`. These are safe to ignore as long as the final message is `Ready to plan`. This confirmation may take up
Should it be "You can start planning now!" ?

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +### Click here to go back to [Phase 3](3_data_collection_model_training.md).
Is this the end? I feel like it needs a big "Congratulations, you got through the demo!!!" The ending doesn't feel final.

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +* **Action**: Return to Unity. Select the `ROSObjects/Publisher` GameObject. Assign the `ur3_with_gripper` GameObject to the `Robot` field. Drag and drop the `Cube` GameObject from the _**Hierarchy**
Now that I've finished I assume it's needed to randomize the cube location, but it might be nice to explain it earlier.

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +You will first need to **clone** this repository. This project has dependencies on a few git submodules, so you'll need to include the flag `--recurse-submodules` in your clone command.
Please verify whether or not git submodules are really used

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +## Requirements
IMO, we can cut a lot of explanation out of this, since it's meant to be a quick demo vs. educational. You should be able to make it as concise as this: https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/pick_and_place/quick_demo.md by strategic hyperlinking.

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +## Requirements
Also, for consistency with the previous tutorial, I suggest changing the section title to "Prerequisites"

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +* **Action**: Go inside the `ROS/SRC/ur3_moveit` folder and create a folder `models`. Copy the `UR3_single_cube_model.tar` file you've just downloaded into this folder.
There should be no "if" on this one; it should simply say "Download the trained model and ...." As such, I think it also makes sense to combine these two actions into one step.

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +## Set up the ROS side
You should also be able to reduce this whole section to something like this: https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/pick_and_place/quick_demo.md#start-ros by moving out all the docker instructions to 0_ros_setup.md and linking to that here.

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +Opening the ROS Settings has created a ROSConnectionPrefab in `Assets/Resources` with the user-input settings. When the static `ROSConnection.instance` is referenced in a script, if a `ROSConnection`
This can be backed into the Unity Project (we did it for P&P)

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +* **Action**: On the `Simulation Scenario` GameObject, uncheck the `Fixed Length Scenario` component to disable it.
Can this be baked into the project?

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +
Can all this be baked into the Unity Project file?

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +**Note**: If you encounter issues with the connection between Unity and ROS, check the [Troubleshooting Guide](troubleshooting.md) for potential solutions.
Again, I think you can take a lot of the explanation out of here, b/c the point isn't to teach but to show.

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +Congrats! You did it!
This is what's missing from the end of part 4!

2021-02-09 02:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +
I think it would be better to end on a note like the P&P quick tutorial: "If you'd now like to follow the full tutorial to learn how to build the pick-and-place simulation from scratch, proceed to Part 1[link]"

2021-02-09 17:24 UTC, sarahwolf32 commented on README.md
> +[Apache License 2.0](LICENSE)
Good question, it shouldn't be. Hmm.

2021-02-10 02:34 UTC, JonathanLeban commented on tutorials/pose_estimation/Documentation/2_set_up_the_data_collection_scene.md
> +You should now have a table, cube, camera, and working robot arm in your scene. In this phase we will prepare the scene for data collection with the Perception package.
@sarah-gibson  because we have the settings of the robot, you think we should delete that still?

2021-02-10 02:37 UTC, JonathanLeban commented on tutorials/pose_estimation/Documentation/2_set_up_the_data_collection_scene.md
> +We need to have a fixed aspect ratio so that you are sure to have the same size of images we have when you collect the data.
it means that we need to change the aspect ratio so that the screenshot we take has the same settings (pixels) that the images we used when we trained our model. @sarah-gibson

2021-02-10 02:37 UTC, JonathanLeban commented on tutorials/pose_estimation/Documentation/2_set_up_the_data_collection_scene.md
> +We need to have a fixed aspect ratio so that you are sure to have the same size of images we have when you collect the data.
is it not clear for you?

2021-02-10 03:33 UTC, JonathanLeban commented on tutorials/pose_estimation/Documentation/2_set_up_the_data_collection_scene.md
> +<img src="Gifs/2_object_position_randomizer.gif" height=388 width=800/>
because we don't rotate the goal

2021-02-10 03:35 UTC, JonathanLeban commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +**Action**: The ROS TCP connection needs to be created. In the top menu bar in the Unity Editor, select `Robotics -> ROS Settings`. Find the IP address of your ROS machine.
I don't understand your commment

2021-02-10 03:37 UTC, JonathanLeban commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +```
@at669

2021-02-10 03:37 UTC, JonathanLeban commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +**Note**: While using the ROS Settings menu is the suggested workflow, you may still manually create a GameObject with an attached ROSConnection component.
@at669

2021-02-10 03:58 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/2_set_up_the_data_collection_scene.md
> +You should now have a table, cube, camera, and working robot arm in your scene. In this phase we will prepare the scene for data collection with the Perception package.
I was thinking to delete because the user hasn't yet verified that everything is working. (Unless you told them to hit play and I missed it.)

2021-02-10 04:05 UTC, JonathanLeban commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +Opening the ROS Settings has created a ROSConnectionPrefab in `Assets/Resources` with the user-input settings. When the static `ROSConnection.instance` is referenced in a script, if a `ROSConnection`
@at669

2021-02-10 04:06 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +**Action**: The ROS TCP connection needs to be created. In the top menu bar in the Unity Editor, select `Robotics -> ROS Settings`. Find the IP address of your ROS machine.
Sorry, I meant one action is inside a bulleted list, and the other action is in a paragraph (so higher level of the document hierarchy). I sort of expected that all the actions would be at one level or the other instead of mixed. This is not that important though. You don't have to change it unless it makes sense to.

2021-02-10 04:06 UTC, JonathanLeban commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +* **Action**: On the `Simulation Scenario` GameObject, uncheck the `Fixed Length Scenario` component to disable it.
you are right

2021-02-10 04:08 UTC, JonathanLeban commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +
no unfortunately... it is part of the Unity editor

2021-02-10 16:04 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/2_set_up_the_data_collection_scene.md
> +<img src="Gifs/2_object_position_randomizer.gif" height=388 width=800/>
Oh, I thought my goal was moving at this point. But I could be mistaken.

2021-02-10 16:36 UTC, at669 commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +```
@sarah-gibson Yes, recent change! Due to the shift to the Hub, this project can't use submodules as the needed ones are already used in `tutorials/pick_and_place`. References to submodules should be removed in this project.

2021-02-10 16:40 UTC, at669 commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +**Note**: While using the ROS Settings menu is the suggested workflow, you may still manually create a GameObject with an attached ROSConnection component.
@sarah-gibson fair point! I actually took this line from the old tutorial ([the Unity side: 9](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/pick_and_place/2_ros_tcp.md#the-unity-side)) with the thought that some users might not be familiar with the singleton pattern, but yes also due to the redundancy of this note it can be deleted

2021-02-10 16:44 UTC, at669 commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +Opening the ROS Settings has created a ROSConnectionPrefab in `Assets/Resources` with the user-input settings. When the static `ROSConnection.instance` is referenced in a script, if a `ROSConnection`
@sarah-gibson the ROSConnection [prefab](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/dextra/PoseEstimation/tutorials/pose_estimation/PoseEstimationDemoProject/Assets/Resources/ROSConnectionPrefab.prefab)/settings are already provided in this project (which the P&P doesn't) as the suggested instructions for this one use Docker. Is this what you mean, or something more specific about the ROS setup?

2021-02-10 16:48 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +Opening the ROS Settings has created a ROSConnectionPrefab in `Assets/Resources` with the user-input settings. When the static `ROSConnection.instance` is referenced in a script, if a `ROSConnection`
@at669 I meant in Peifeng's quick start demo, we don't need to adjust any setting in Unity, so presumably it's somehow already set in the Project?

2021-02-10 16:59 UTC, at669 commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +Opening the ROS Settings has created a ROSConnectionPrefab in `Assets/Resources` with the user-input settings. When the static `ROSConnection.instance` is referenced in a script, if a `ROSConnection`
I see! I think he [manually creates the ROSConnection object](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/f2dbd33473695db7e7fea894bfd57dba6e5da0c6/tutorials/pick_and_place/PickAndPlaceProject/Assets/DemoScripts/Demo.cs#L156) in the demo script. Technically, since we provide the prefab in this project, the user doesn't strictly need to do this step if using the provided project, but it's still provided for both users using their project from scratch and explaining non-Docker steps

2021-02-10 17:14 UTC, sarah-gibson commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +Opening the ROS Settings has created a ROSConnectionPrefab in `Assets/Resources` with the user-input settings. When the static `ROSConnection.instance` is referenced in a script, if a `ROSConnection`
@at669 I see. The main spirit of my comments here is I'm trying to strip out any unnecessary steps so that the "quick demo" actually looks quick. More streamlined like [this](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/f2dbd33473695db7e7fea894bfd57dba6e5da0c6/tutorials/pick_and_place/quick_demo.md). So if I'm understanding correctly, if the user doesn't need to do the steps to run the quick demo, we should remove them. The full instructions will still exist in the other parts of the tutorial.

2021-02-10 17:23 UTC, at669 commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +Opening the ROS Settings has created a ROSConnectionPrefab in `Assets/Resources` with the user-input settings. When the static `ROSConnection.instance` is referenced in a script, if a `ROSConnection`
@sarah-gibson OH. noticing that this was a comment on the quick demo was the key part of this conversation I was missing 🤦‍♀️  yes, if this is in the quick demo and they're running the docker setup, this should be removed

2021-02-10 22:34 UTC, sarahwolf32 commented on tutorials/pose_estimation/Documentation/4_pick_and_place.md
> +**Note**: The launch file may throw errors regarding `[controller_spawner-5] process has died`. These are safe to ignore as long as the final message is `Ready to plan`. This confirmation may take up
Note: Need to go back and fix this again. Need to include the `Ready to plan.`

2021-02-11 02:18 UTC, sarahwolf32 commented on tutorials/pose_estimation/Documentation/quick_demo_full.md
> +## Set up the ROS side
We've decided to keep it as is.

2021-02-11 17:33 UTC, sarah-gibson approved these changes
Great job, all!

2021-02-11 17:37 UTC, merged