Vidur/updating ros unity tutorials
Unity-Technologies/Unity-Robotics-Hub pull request #221
Opened 2021-05-13 03:42 UTC by vidurvij-Unity

## Proposed change(s)

Adds a section in publisher and subscriber tutorials describing the ROSSubscriber and ROSPublisher  example scripts and the  APIs used in them.

### Useful links (GitHub issues, JIRA tickets, forum threads, etc.)

Provide any relevant links here.

https://jira.unity3d.com/browse/AIRO-593
https://github.com/Unity-Technologies/Unity-Robotics-Hub/issues/196
### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [x] Documentation update
- [ ] Other (please describe)

## Testing and Verification

Did a spellcheck and grammar check.

### Test Configuration:
- Unity Version: [e.g. Unity 2020.2.0f1]
- Unity machine OS + version: [e.g. Windows 10]
- ROS machine OS + version: [e.g. Ubuntu 18.04, ROS Noetic]
- ROS–Unity communication: [e.g. Docker]

## Checklist
- [x] Ensured this PR is up-to-date with the `dev` branch
- [x] Created this PR to target the `dev` branch
- [ ] Followed the style guidelines as described in the [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] Added tests that prove my fix is effective or that my feature works
- [x] Updated the documentation as appropriate

## Other comments

2021-07-06 19:54 UTC, hyounesy requested changes
- [ ] Remove the dublicate ROSPublisher code block.
 - [ ] Fix inconsistent indentations
 - [ ] Fix typos

2021-07-06 19:54 UTC, hyounesy commented on tutorials/ros_unity_integration/publisher.md
> +
This entire code block was previously shown. what is the purpose for repeating it?

2021-07-06 19:54 UTC, hyounesy commented on tutorials/ros_unity_integration/publisher.md
> +## ROSSPublisherExample script
typo: ROS~~S~~PublisherExample

2021-07-06 19:54 UTC, hyounesy commented on tutorials/ros_unity_integration/publisher.md
> +```
inconsistent indentation

2021-07-06 19:54 UTC, hyounesy commented on tutorials/ros_unity_integration/publisher.md
> +            );
inconsistent indentation

2021-07-06 19:54 UTC, hyounesy commented on tutorials/ros_unity_integration/subscriber.md
> +    }
inconsistent indentation

2021-07-06 19:54 UTC, hyounesy commented on tutorials/ros_unity_integration/subscriber.md
> +    }
inconsistent indentation

2021-07-06 19:54 UTC, hyounesy commented on tutorials/ros_unity_integration/subscriber.md
> +T: ROS message type published in the topic to be subscribed.
Can this sentence be simplified to read better. It took me some effort to parse it in my head. something like:
"Type of the ROS message that we are subscribing to."

2021-07-06 19:54 UTC, hyounesy commented on tutorials/ros_unity_integration/subscriber.md
> +After a message is received in Unity, a callback function is called to process the incoming message. The callback is a delegate which defines a function that receives one parameter and returns nothin
"published ~~in~~ [to] the topic"

2021-07-06 19:54 UTC, hyounesy commented on tutorials/ros_unity_integration/publisher.md
> +Its a non-static member of ROSConnection class. Its used to send a ROS message to the desired topic on the ROS machine.
It~~s~~ [is] used to send a ROS message to the ~~desired~~ [specified] topic ...

2021-07-06 20:21 UTC, LaurieCheers-unity commented on tutorials/ros_unity_integration/publisher.md
> +            MPosRot cubePos = new MPosRot(
This is old code, need to merge the latest changes to dev branch

2021-07-28 17:27 UTC, sdiao commented
@vidurvij-Unity Is this PR still relevant? Should we close it without merging?

2021-07-29 21:25 UTC, vidurvij-Unity commented
The tutorial update is deprecated.

2021-07-29 21:25 UTC, closed without merging