Adding primitive sizing documentation
Unity-Technologies/Unity-Robotics-Hub pull request #222
Opened 2021-05-13 06:16 UTC by vidurvij-Unity

## Proposed change(s)
The original issue described the inability of the user to export the size of the primitive he created to the URDF file. He was trying to export the size of the box he created to a URDF file using the export feature but the URDF file always exported the size [1 1 1]. This is an expected behavior because URDF importer does not read or write size of the primitives in the [BoxCollider](https://docs.unity3d.com/ScriptReference/BoxCollider-size.html), CapsuleCollider or the Spherical Collider. Instead it change the size of the visual and collider meshes using the scale of the parent gameObject of the mesh. 

This is done because:
1. To have consistency between the way the size of the mesh is changed between primitive collider meshes and other meshes.
2. This API also works by changing the scale of the mesh under the hood. 
### Useful links (GitHub issues, JIRA tickets, forum threads, etc.)

https://jira.unity3d.com/browse/AIRO-623
https://github.com/Unity-Technologies/URDF-Importer/issues/79

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [x] Documentation update
- [ ] Other (please describe)

## Testing and Verification

Test the bug by importing and exporting R2D2 URDF file which is made up box primitives.

### Test Configuration:
- Unity Version: [e.g. Unity 2020.2.0f1]
- Unity machine OS + version: [e.g. Windows 10]
- ROS machine OS + version: [e.g. Ubuntu 18.04, ROS Noetic]
- ROS–Unity communication: [e.g. Docker]

## Checklist
- [x] Ensured this PR is up-to-date with the `dev` branch
- [x] Created this PR to target the `dev` branch
- [ ] Followed the style guidelines as described in the [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] Added tests that prove my fix is effective or that my feature works
- [x] Updated the documentation as appropriate

## Other comments

2021-05-13 19:40 UTC, sarah-gibson requested changes

2021-05-13 19:40 UTC, sarah-gibson commented on tutorials/urdf_importer/urdf_appendix.md
> +The size of the primitive will be set in Unity by changing the scale of gameObject containing UrdfCollision script.
This is passive voice, which is a bit confusing. Who will do the setting? Is it the URDF Importer? If so, here's a suggestion: "The URDF Importer will set the size of the primitive using the "scale" parameter of the GameObject that contains the UrdfCollsion script." [if the meaning is still correct]

2021-05-13 19:40 UTC, sarah-gibson commented on tutorials/urdf_importer/urdf_appendix.md
> +This is done, as opposed to using the size API of the primitive collider, to have consistency across different mesh types. The sizing API is only available for primitive mesh colliders and not for co
Suggestion to improve clarity:
"The reason we set the size via the "scale" of the parent GameObject as opposed to the "size" of the primitive collider is to have consistency across different mesh types; the size API is only available for primitive mesh colliders and not for complex collider meshes and visual meshes, whose size must be changed using their parent GameObject's "scale" parameter."

2021-05-13 19:40 UTC, sarah-gibson commented on tutorials/urdf_importer/urdf_appendix.md
> +This is done, as opposed to using the size API of the primitive collider, to have consistency across different mesh types. The sizing API is only available for primitive mesh colliders and not for co
I don't understand what the last sentence means - can you clarify?

2021-06-07 13:58 UTC, vidurvij-Unity commented on tutorials/urdf_importer/urdf_appendix.md
> +This is done, as opposed to using the size API of the primitive collider, to have consistency across different mesh types. The sizing API is only available for primitive mesh colliders and not for co
Updated the language

2021-06-07 23:51 UTC, sarah-gibson approved these changes
Looks good, but since this is getting so long, it would be nice to put a TOC on top!

2021-06-30 17:59 UTC, hyounesy commented on tutorials/urdf_importer/urdf_appendix.md
> + <collision>
nit: remove extra space.

2021-06-30 18:05 UTC, hyounesy commented on tutorials/urdf_importer/urdf_appendix.md
> +The reason we set the size via the "scale" of the parent GameObject as opposed to the "size" of the primitive collider is to have consistency across different mesh types; the size API is only availab
- ... is also used [to] set the values of [the] primitive['s] ...
- ... performing [a] URDF export.

2021-06-30 18:13 UTC, hyounesy requested changes
- The example xml needs to be corrected.
- Also some minor typos.

2021-06-30 18:13 UTC, hyounesy commented on tutorials/urdf_importer/urdf_appendix.md
> +<collision>
remove the extra <collision> tag at the bottom and reformat:
``` xml
<collision>
  <geometry>
    <cylinder size=".4 .3 .4" />
  </geometry>
</collision>
```

2021-06-30 18:13 UTC, hyounesy commented on tutorials/urdf_importer/urdf_appendix.md
> +URDF defines the robot visually using Visual Meshes, and its collision using Collision Meshes. Collision meshes define the physical volume of the links, and are used to calculate the inertia of the l
nit:  Rigidbody
Perhaps you can also link it to the documentation. e.g.: 
In Unity, [Rigidbody](https://docs.unity3d.com/ScriptReference/Rigidbody.html) components cannot ...

2021-07-06 20:43 UTC, hyounesy approved these changes

2021-07-06 20:43 UTC, hyounesy commented on tutorials/urdf_importer/urdf_appendix.md
> +URDF defines the robot visually using Visual Meshes, and its collision using Collision Meshes. Collision meshes define the physical volume of the links, and are used to calculate the inertia of the l
consistency nit: Rigid~~B~~[b]odies, or better [Rigidbody components]

2021-07-06 23:42 UTC, merged