AIRO-1431 Add ros integration tests
Unity-Technologies/Unity-Robotics-Hub pull request #329
Opened 2021-10-28 00:16 UTC by peifeng-unity

## Proposed change(s)

Add Yamato integration tests for ROS integration

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update
- [x] Other: tests

## Checklist
- [] Ensured this PR is up-to-date with the `dev` branch
- [ ] Created this PR to target the `dev` branch
- [ ] Followed the style guidelines as described in the [Contribution Guidelines](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/CONTRIBUTING.md)
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [Changelog](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/dev/CHANGELOG.md) and described changes in the [Unreleased section](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/dev/CHANGELOG.md#unreleased)
- [ ] Updated the documentation as appropriate

## Other comments

2021-11-03 21:01 UTC, mrpropellers requested changes

2021-11-03 21:01 UTC, mrpropellers commented on tutorials/pick_and_place/PickAndPlaceProject/Assets/Tests/EditMode/RosIntegrationTests.cs
> +            PlayerSettings.SetScriptingDefineSymbolsForGroup(buildTargetGroup, string.Join(";", allDefines));
If every yamato trigger => one test run for a specific ros distro and build target, then these seem like things that could be configured before Unity even starts up, right?  Otherwise we will sometimes have to wait for Unity to build everything for the wrong distro and platform and rebuild for the ones we want before starting the tests.

2021-11-04 17:59 UTC, peifeng-unity commented on .yamato/PickAndPlaceTests/ros.bash
> +  echo "Completed to run $ROS color publisher"
Ah, sure, updated.

2021-11-04 17:59 UTC, peifeng-unity commented on .yamato/PickAndPlaceTests/ros.bash
> +# Assuming this script is invoked from the root of the repository...
Sure, just updated

2021-11-04 17:59 UTC, peifeng-unity commented on .yamato/yamato-config.yml
> +      NOT pull_request.changes.all match ["**/*.md","**/*.jpg","**/*.jpeg","**/*.gif","**/*.pdf"])
Yep, added.

2021-11-04 18:00 UTC, peifeng-unity commented on tutorials/pick_and_place/PickAndPlaceProject/Assets/Tests/EditMode/RosIntegrationTests.cs
> +                "The dependencies of this test are not guaranteed to exist in the Project by default.");
Okay, updated

2021-11-04 18:13 UTC, peifeng-unity commented on .yamato/PickAndPlaceTests/ros.bash
> +    sleep 30
Ah, good questions! Here are my thoughts when setting it to these numbers

1. the timeout on the Unity side is 60 seconds, so 30 seconds will guarantee that Unity will receive 1-2 message when the corresponding tests are running
2. because we have 4 integration tests running sequentially and the ROS calls start before the 4 tests are triggered. It is uncertain when a test (e.g. the color subscriber in Unity) will start to run. Might be 10 seconds after running the `utr` command or it could be more than 1 minute. The total tests may take about 3 minutes (depending on how long it starts Unity), so 2 or 3 times may not be enough to guarantee. I probably could reduce it to 5 or 6 times I guess? Just updated it to 5.
3. yeah, the color publisher exit right after they're started (it takes about < 1s) [[ref](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/ros_unity_integration/ros_packages/unity_robotics_demo/scripts/color_publisher.py#L46)]

2021-11-04 18:14 UTC, peifeng-unity commented on .yamato/yamato-config.yml
> +      export ROS_DISTRO=$(ls -1 /opt/ros | head -n1)
ah, yeah, okay. I added a TODO comment to move the ROS_DISTRO export to the image builder side :)

2021-11-04 18:16 UTC, peifeng-unity commented on .yamato/yamato-config.yml
> +      sleep 10  # Wait for ROS endpoint to stand up
Yeah, this is only for ROS1. ROS2 will work fine without waiting 10 seconds. In ROS1, the `start_ros` command does two things: 1) start ros master 2) start ros_tcp_endpoint. The wait inside the ros.bash is to wait for ros master, and the wait here (10 sec) is for ros_master + ros_tcp_endpoint...

2021-11-04 18:20 UTC, peifeng-unity commented on .yamato/yamato-config.yml
> +      NOT pull_request.changes.all match ["**/*.md","**/*.jpg","**/*.jpeg","**/*.gif","**/*.pdf"])
Ah, good point! There will be three Yamato jobs running in parallel (Pick-and-Place, noetic, and galactic), they took almost the same amount of time (PnP: [12m 37s](https://unity-ci.cds.internal.unity3d.com/job/9744586), [noeitc: 12m 44s](https://unity-ci.cds.internal.unity3d.com/job/9744584), [galactic: 13m 03s](https://unity-ci.cds.internal.unity3d.com/job/9744585)). So I guess they won't increase our Yamato time?

2021-11-05 19:43 UTC, peifeng-unity commented on tutorials/pick_and_place/PickAndPlaceProject/Assets/Tests/EditMode/RosIntegrationTests.cs
> +using UnityEditor;
Yeah, the UnityEditor is used by switching the RosProtocol. If we could remove the switching ROS protocol part from the code, we should be able to make it working in the standalone player.

2021-11-05 21:12 UTC, LaurieCheers-unity commented on tutorials/pick_and_place/PickAndPlaceProject/Assets/Tests/EditMode/RosIntegrationTests.cs
> +using UnityEditor;
Does the pick and place project even work with ROS2?

2021-11-05 21:19 UTC, peifeng-unity commented on tutorials/pick_and_place/PickAndPlaceProject/Assets/Tests/EditMode/RosIntegrationTests.cs
> +using UnityEditor;
Ah, pick-and-place only works with ROS1. These integration tests in this PR are moving [these tutorials](https://github.com/Unity-Technologies/Unity-Robotics-Hub/tree/main/tutorials/ros_unity_integration) to Yamato.

2021-11-05 21:20 UTC, peifeng-unity commented on tutorials/pick_and_place/PickAndPlaceProject/Assets/Tests/EditMode/RosIntegrationTests.cs
> +using UnityEditor;
I got it working to set the preprocessor directives in the ProjectSettings.assets. Just updated the PR and removed the UnityEditor from this test script.

2021-11-05 21:20 UTC, peifeng-unity commented on tutorials/pick_and_place/PickAndPlaceProject/Assets/Tests/EditMode/RosIntegrationTests.cs
> +            PlayerSettings.SetScriptingDefineSymbolsForGroup(buildTargetGroup, string.Join(";", allDefines));
Good point. Just got it working to set the preprocessor directives in the ProjectSettings.assets. Updated the PR.

2021-11-08 20:03 UTC, mrpropellers approved these changes

2021-11-08 20:14 UTC, merged