Unity server update
Unity-Technologies/Unity-Robotics-Hub pull request #49
Opened 2020-11-13 00:45 UTC by LaurieCheers-unity

2020-11-17 18:47 UTC, mrpropellers commented
> No description provided.  

PR needs a description - preferably at a minimum containing the following:
1. What the issue/problem was
2. How it was fixed
3. How you fix was tested to confirm a) the issue is resolved and b) nothing else broke  

It's fine to copy the description across to all the open PRs for this change

2020-11-17 19:00 UTC, peifeng-unity reviewed
Is this change backward compatible?
Also, I guess it is tested in ros noetic; is it compatible with ros melodic?

2020-11-17 19:00 UTC, peifeng-unity commented on tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py
> +    ros_tcp_port = rospy.get_param("/ROS_TCP_PORT", 10000)
nit: is it possible to parameterize the port 10000?

2020-11-17 19:00 UTC, peifeng-unity commented on tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py
> +    unity_machine_ip = rospy.get_param("/UNITY_IP", '')
nit: same, is it possible to parameterize the IP string ''?

2020-11-17 19:00 UTC, peifeng-unity commented on tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py
> +    unity_machine_port = rospy.get_param("/UNITY_SERVER_PORT", 5005)
nit: same, is it possible to parameterize the port 5005?

2020-11-17 19:00 UTC, peifeng-unity commented on tutorials/ros_packages/robotics_demo/scripts/server_endpoint.py
> +    ros_tcp_port = rospy.get_param("/ROS_TCP_PORT", 10000)
nit: same, is it possible to parameterize the port 10000?

2020-11-17 19:00 UTC, peifeng-unity commented on tutorials/ros_packages/robotics_demo/scripts/server_endpoint.py
> +    unity_machine_port = rospy.get_param("/UNITY_SERVER_PORT", 5005)
nit: same, is it possible to parameterize port number 5005?

2020-11-17 19:00 UTC, peifeng-unity commented on tutorials/ros_packages/robotics_demo/scripts/server_endpoint.py
> +    unity_machine_ip = rospy.get_param("/UNITY_IP", '')
nit: same; is it possible to parameterize the empty string?

2020-11-17 19:01 UTC, LaurieCheers-unity commented on tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py
> +    ros_tcp_port = rospy.get_param("/ROS_TCP_PORT", 10000)
This line IS reading the parameter ROS_TCP_PORT. The default is 10000 in the event that it's not defined.

2020-11-17 19:03 UTC, LaurieCheers-unity commented on tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py
> +    unity_machine_ip = rospy.get_param("/UNITY_IP", '')
In the rest of the code, the empty string is interpreted as a special value that means "IP has not been overridden, deduce the IP automatically". Is there maybe a better value to use for that?

2020-11-17 19:04 UTC, peifeng-unity commented on tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py
> +    ros_tcp_port = rospy.get_param("/ROS_TCP_PORT", 10000)
Yeah, sorry, I meant whether we could parameterize the default port number because I saw that it is used in a couple of places?

2020-11-17 19:04 UTC, LaurieCheers-unity commented on tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py
> +    unity_machine_port = rospy.get_param("/UNITY_SERVER_PORT", 5005)
Again, not really sure what you're asking for, this line IS reading the parameter UNITY_SERVER_PORT. I'm just adding a fallback in case it wasn't defined.

2020-11-17 19:08 UTC, LaurieCheers-unity commented
> Is this change backward compatible?

No, the change is not backward compatible. Anyone writing their own server_endpoint needs to change it a little. On the Unity side, RosSubscriber ceased to exist, so anyone deriving from that class has to rewrite.

> Also, I guess it is tested in ros noetic; is it compatible with ros melodic?

It's been tested in both. This version is compatible with ros melodic, there will be some separate PRs to make our codebase noetic compatible.

2020-11-17 19:11 UTC, LaurieCheers-unity commented on tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py
> +    ros_tcp_port = rospy.get_param("/ROS_TCP_PORT", 10000)
Like, you want to make it a global variable?

2020-11-17 19:21 UTC, mrpropellers requested changes

2020-11-17 19:21 UTC, mrpropellers commented on tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py
> +from tcp_endpoint.UnityTCPSender import UnityTCPSender
The syntax of this import statement suggests that we're doing something weird with the structure of this module.  Are we missing the `from . import *` statement (or similar) in the __init__.py file? It'd be more PEP-8ish to be able to write this as `from tcp_endpoint import UnityTCPSender` and likewise for the import lines immediately below.

2020-11-17 19:23 UTC, LaurieCheers-unity commented on tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py
> +from tcp_endpoint.UnityTCPSender import UnityTCPSender
Thanks. I didn't intend to do anything weird, my Python experience is limited so I'm not sure what a normal import looks like.

2020-11-17 21:23 UTC, peifeng-unity commented
> > Is this change backward compatible?
> 
> No, the change is not backward compatible. Anyone writing their own server_endpoint needs to change it a little. On the Unity side, RosSubscriber ceased to exist, so anyone deriving from that class has to rewrite. (The replacement code is much cleaner - see tutorials/ros_unity_integration/unity_scripts/RosSubscriberExample.cs. And those not using RosSubscriber shouldn't have any problems.)

Do we also need to update the ros_tcp_endpoint submodule (https://github.com/Unity-Technologies/Unity-Robotics-Hub/tree/main/tutorials/pick_and_place/ROS/src) to a new commit?

If it is not backward compatible, would it be good to release the changes by simply merging to the main branch?

2020-11-17 21:37 UTC, LaurieCheers-unity commented
> Do we also need to update the ros_tcp_endpoint submodule (https://github.com/Unity-Technologies/Unity-Robotics-Hub/tree/main/tutorials/pick_and_place/ROS/src) to a new commit?

Probably? It should fetch the commit from the other PR. Not sure if that needs to be done manually.

> If it is not backward compatible, would it be good to release the changes by simply merging to the main branch?

You mean, would it would be a bad idea to simply merge it? I don't know, what do people think?

2020-11-17 22:39 UTC, peifeng-unity commented
> > Do we also need to update the ros_tcp_endpoint submodule (https://github.com/Unity-Technologies/Unity-Robotics-Hub/tree/main/tutorials/pick_and_place/ROS/src) to a new commit?
> 
> Probably? It should fetch the commit from the other PR. Not sure if that needs to be done manually.

I think it needs to be updated manually (like https://stackoverflow.com/questions/8191299/update-a-submodule-to-the-latest-commit)

> > If it is not backward compatible, would it be good to release the changes by simply merging to the main branch?
> 
> You mean, would it would be a bad idea to simply merge it? I don't know, what do people think?

Yeah, we may need a team discussion?

2020-11-18 20:40 UTC, mrpropellers submitted a review, later dismissed
Nothing major left I don't think, although you should make sure to merge changes from the upstream packages first, update the tagged version, and commit the new versions to the package manifest and submodules here before merging this.

2020-11-18 21:41 UTC, LaurieCheers-unity commented on tutorials/pick_and_place/ROS/src/niryo_moveit/config/params.yaml
> +ROS_IP: 192.168.1.88
Good call.

2020-11-23 17:56 UTC, mpinol submitted a review, later dismissed

2020-11-23 19:30 UTC, mrpropellers submitted a review, later dismissed

2020-11-23 20:08 UTC, mrpropellers submitted a review, later dismissed

2020-11-23 20:47 UTC, mpinol approved these changes

2020-11-23 20:47 UTC, merged