Updating Robotics Hub without references to VHACD
Unity-Technologies/Unity-Robotics-Hub pull request #52
Opened 2020-11-13 20:46 UTC by vidurvij-Unity

2020-11-13 20:58 UTC, hyounesy commented on tutorials/pick_and_place/PickAndPlaceProject/Packages/manifest.json
> +    "com.unity.robotics.urdf-importer": "git+https://github.com/Unity-Technologies/URDF-Importer.git#v0.0.3-no-vhacd",
should also commit the packages-lock.json.

2020-11-13 21:00 UTC, hyounesy requested changes
should also commit the packages-lock.json with the updated "version" and "hash":
```
"version": "git+https://github.com/Unity-Technologies/URDF-Importer.git#v0.0.3-no-vhacd",
...
"hash": "32c1a31bdeebd08db3e6aff511f0f23609c7a82f"
```

2020-11-13 21:25 UTC, at669 commented
@vidurvij-Unity I'm still running into issues opening the project--might need to clear out [URDF gitmodules](https://github.com/Unity-Technologies/URDF-Importer/blob/vidur/URDF_without_VHACD/.gitmodules) or else it still seems to try to pull the repo

2020-11-13 21:32 UTC, peifeng-unity commented
@vidurvij-Unity Also could we update the instruction and let people not use VHACD?
https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/912e28158b38d3723a69f6df59b9427a9cc9040a/tutorials/pick_and_place/1_urdf.md

2020-11-13 22:48 UTC, at669 approved these changes

2020-11-13 23:12 UTC, peifeng-unity approved these changes

2020-11-13 23:17 UTC, hyounesy approved these changes

2021-08-05 21:21 UTC, vidurvij-Unity commented
This PR was meant to be a placeholder for URDF Importer, in case we didn't receive authorization to use VHACD. I think we are are passed that.

2021-08-05 21:21 UTC, closed without merging