Add pick&place docker
Unity-Technologies/Unity-Robotics-Hub pull request #65
Opened 2020-12-01 17:05 UTC by peifeng-unity

Package ROS side services into a docker container so that users could skip the preparations of the ROS environment. Tested on macOS and Ubuntu, and both work well.

2020-12-01 20:28 UTC, mrpropellers requested changes
Requesting a small change to the tutorial - otherwise looks like a good addition!

2020-12-01 20:28 UTC, mrpropellers commented on tutorials/pick_and_place/3_pick_and_place.md
> +  docker run -it --rm -p 10000:10000 -p 5005:5005 unity-robotics:pick-and-place part_3 /bin/bash
I'd include a link here to the docker build instructions in Part 2 in case a user has skipped ahead or is for some other reason confused about where this container came from.

2020-12-03 00:04 UTC, mrpropellers approved these changes

2020-12-07 22:44 UTC, mrpropellers approved these changes

2020-12-07 23:07 UTC, peifeng-unity commented
Thank @mrpropellers that the docker build and run would work on Windows, macOS, and Ubuntu platforms.

2020-12-07 23:08 UTC, merged