WIP: Mpinol/simreal
Unity-Technologies/Unity-Robotics-Hub pull request #86
Opened 2021-01-04 18:59 UTC by mpinol

2021-01-20 00:04 UTC, sarah-gibson requested changes

2021-01-20 00:04 UTC, sarah-gibson commented on tutorials/pick_and_place/README.md
> +## [Part 4: Pick-and-Place Sim and Real](4_sim_and_real.md)
What about calling it something like "Pick-and-place on the real robot" and then change Part 3 to "Pick-and-place in Unity"

2021-01-20 00:04 UTC, sarah-gibson commented on tutorials/pick_and_place/4_sim_and_real.md
> +- The `pick_and_place` function has been updated to call the two previous functions instead of appening the trajectory or gripper command to a list.
appending

2021-01-20 00:04 UTC, sarah-gibson commented on tutorials/pick_and_place/README.md
> +## [Part 4: Pick-and-Place Sim and Real](4_sim_and_real.md)
TODO - add gif

2021-01-22 00:35 UTC, at669 commented on tutorials/pick_and_place/README.md
> +  - [Part 4: Pick-and-Place On Robot](#part-4-pick-and-place)
These two links don't work anymore (re: "in unity/on robot")--I've been using [Markdown All In One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) to auto-generate the TOC and edit as needed

2021-01-22 00:35 UTC, at669 commented on tutorials/pick_and_place/4_pick_and_place.md
> +## Differences From Part 3
nit: just to be explicit, maybe specifying specifically "Purely simulated" vs "Simulated and real" as opposed to "Part 3" and "Part 4?"

2021-01-22 00:35 UTC, at669 commented on tutorials/pick_and_place/4_pick_and_place.md
> +**Part 4 Flow:**
It might be easier to digest the steps wrt the diagram with numbered steps, and corresponding numbered arrows for the diagram?

2021-01-22 00:35 UTC, at669 commented on tutorials/pick_and_place/4_pick_and_place.md
> +            StartCoroutine(ExecuteTrajectories(robotAction.goal.cmd.Trajectory.trajectory));
I haven't thought about this before, but coroutines are something a lot of non-Unity users may not be familiar with--do you think this is something worth explaining or linking out to, either here, or in Part 3?

2021-01-22 00:35 UTC, at669 commented on tutorials/pick_and_place/4_pick_and_place.md
> +- To account for the simulated Niryo One's position on a table, the URDF files on the Niryo One will need to be updated to reflect this change.
this is briefly mentioned in Part 1, `Note: The world-space origin of the robot is defined in its URDF file. In this sample, we have assigned it to sit on top of the table, which is at (0, 0.63, 0) in Unity coordinates...`--I think you can specify that the provided URDF has this change already applied, and/or mention something about how "the base of the Niryo One URDF needs to reflect its simulated height on the table..." and maybe be a little more explicit that its simulated positioning is used in trajectory calculations? or this can also be added to Part 1

2021-01-22 00:35 UTC, at669 commented on tutorials/pick_and_place/4_pick_and_place.md
> +- Update the `niryo_moveit/config/params.yml` file's `ROS_IP` parameter to match that of the Niryo One.
an example `echo "ROS_IP: ... ` command could be helpful here

2021-01-22 00:35 UTC, at669 commented on tutorials/pick_and_place/4_pick_and_place.md
> +
in addition to describing the action server, I think it would help to have a more clear high level of what is changing, e.g. "... as well as describing the necessary modifications of using a ROS Subscriber ... in place of the Mover ROS Service from previous steps...",  etc ?

2021-01-27 00:15 UTC, at669 approved these changes

2021-01-29 01:53 UTC, sarah-gibson requested changes

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +The best source of information for the Niryo One is the [User Manual](https://niryo.com/docs/niryo-one/user-manual/complete-user-manual/). It contains a lot of general information about the Niryo One
"connecct" typo

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +For this tutorial we will be using the full [Niryo One ROS](https://niryo.com/docs/niryo-one/developer-tutorials/get-started-with-the-niryo-one-ros-stack/) stack running on the Niryo One robot.
nit - include "stack" in the hyperlink

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +The `goal` section in the `niryo_one_msgs/action/RobotMove.action` file shows a single parameter, `RobotMoveCommand`. Then looking at the `RobotMoveCommand` message we see that it is used as a catch
"catchall" is one word

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +The `goal` section in the `niryo_one_msgs/action/RobotMove.action` file shows a single parameter, `RobotMoveCommand`. Then looking at the `RobotMoveCommand` message we see that it is used as a catch
Would "field" be a better word than "parameter"?

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +Since the `cmd_type` variable is used to determine which command in the `RobotMoveCommand` message is to be executed, we will need to find the appropriate values to exectue trajectory or tool command
"execute" typo

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +	- Which end effector is being used **TODO: How do we know 11**
You have a todo!

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +![](img/4_new_flow.png)
nit - change 3.1 and 3.2 to 3.i and 3.ii to match markdown numbering

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +**Changes:**
Note the changes between Part 3 and Part 4:

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +- Introduction of an action server, `RobotMove`, to schedule and exectute trajectories.
Change this to a complete system, for parallelism: "An action server, `RobotMove`, has been introduced to schedule and execute trajectories.

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +- Gripper command execution was previously hard coded in `TrajectoryPlanner.cs` in part 3 but is now being managed by the `RobotMove` action server.
hyphenate "hard-coded"

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +- The `MoverService`, `mover.py`,  has been replaced with a ROS Subscriber in `sim_and_real_pnp.py` but retains the trajectory planning capability.
Hyphenate "trajectory-planning" since it's a compound adjective

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +Instead of calling a service and waiting for the response  to execute a robot command, a subscription is going to be made to the `niryo_one/commander/robot_action/goal` topic and every command publis
upon "receipt" sounds better I think. Otherwise it sounds like football.

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +## Setting Up Unity Scene
Setting Up "the" Unity Scene

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +1. In Unity, Select Robotics -> ROS Settings from the top menu bar and update the ROS IP Address to that of the Niryo One.
I'm assuming the Niryo One must be on the same network as Unity?

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +1. Select the previously made Button object in Canvas/Button, and scroll to see the Button component. Under the `OnClick()` header, click the dropdown where it is currently assigned to the SourceDest
The numbering restarted here for some reason

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +1. The Unity side is now ready to communicate with ROS on the Niryo One!
Restarted again

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +> An easy way to find the Niryo One's IP address is to connect to it using the Niryo One Studio application
Might want to move this comment earlier, since you had to use its IP address in the previous section as well

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +	- `roslaucnh niryo_moveit part_4.launch`
typo: "roslaunch"

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +---
plz delete

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +---
plz delete

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +---
plz delete

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +## RobotMoveGoal Parameters
The hierarchy here doesn't match the table of contents

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +- Copy the `niryo_moveit` package to the `catkin_ws` directory on the Niryo One's catkin workspace at `/home/niryo/catkin_ws` and run the `catkin_make` command.
Is this the only package running on the robot? Or are all the nodes? Based on the diagram at the top, I thought all the nodes would be, but if that's the case, then this line is confusing. Is it assuming you already copied all the other needed packages?

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/4_pick_and_place.md
> +![](img/4_old_flow.png)
Both of these diagrams are great! But they show up pixelated on my screen. Can you capture them with better resolution?

2021-01-29 01:53 UTC, sarah-gibson commented on tutorials/pick_and_place/README.md
> +  - [Part 4: Pick-and-Place On Robot](#part-4-pick-and-place-on-robot)
"Pick-and-Place on the Real Robot"

2021-02-02 19:26 UTC, closed without merging