AIRO-356: Tutorial Updates
Unity-Technologies/Unity-Robotics-Hub pull request #88
Opened 2021-01-06 20:58 UTC by at669

- More explanation on location of windows, menu options
- Highlighted sections of screenshots in Part 1
- Minor clarifications, additional screenshots
- Moved the default target/targetPlacement objects to the "front" (on the Unity logo) such that the action happens "in front of the camera" as seen below:
![Screen Shot 2021-01-06 at 1 57 18 PM](https://user-images.githubusercontent.com/31416491/103819163-1dde8100-5027-11eb-8b20-3702712ac9fb.png)

2021-01-07 18:49 UTC, mpinol commented on tutorials/pick_and_place/2_ros_tcp.md
> +   In the Message Auto Generation window click `Browse File...` and navigate to the MoveIt Msgs directory in this cloned repository (`Unity-Robotics-Hub/tutorials/pick_and_place/ROS/src/moveit_msgs`)
Would it make sense to change the message generation steps to use the new MessageGenerationBrowser?

2021-01-12 21:19 UTC, LaurieCheers-unity requested changes

2021-01-12 21:19 UTC, LaurieCheers-unity commented on tutorials/pick_and_place/2_ros_tcp.md
> +   In the ROS Settings window, the `Host Name` should be the IP address of your ROS machine (*not* the one running Unity).
The field is called "ROS IP Address"

2021-01-12 22:43 UTC, LaurieCheers-unity approved these changes

2021-01-13 22:22 UTC, sarah-gibson approved these changes
Approved, pending:
1) fix the echo ROS_IP problem in Dockerfile
2) check on the issue with not being able to pick up the cube

2021-01-14 00:08 UTC, at669 commented
> 1. fix the echo ROS_IP problem in Dockerfile

removed echo from Dockerfile, moved to `set up workspace` script. appears to be functional for me--added some troubleshooting tips just in case

> 2. check on the issue with not being able to pick up the cube

swapped gripper open/close values to match changes in Unity-Technologies/Unity-Robotics-Hub#84

2021-01-14 00:09 UTC, merged